version: '3.8'

services:
  db:
    image: postgres:15
    container_name: laose_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
      POSTGRES_DB: your_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: laose_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://your_pg_user:your_pg_password@db:5432/your_db_name
      JWT_SECRET: your_jwt_secret
      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret
      STRIPE_SECRET_KEY: your_stripe_secret_key
      STRIPE_WEBHOOK_SECRET: your_stripe_webhook_secret
      CLIENT_URL: http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  pgdata:
